---
dist: xenial
sudo: required
language: python
services:
  - docker
python: '3.7'

before_script:
  - cd ../
  - mv ansible-role-cron daixijun.cron
  - cd daixijun.cron

install:
  - pip install ansible molecule docker
  - pip install --upgrade testinfra

script:
  - molecule test

notifications:
  email: false
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
